import images from './images';

const wines = [
  {
    title: 'Baden Baden',
    price: 'R$ 24',
    tags: 'Witbier, Ippa',
  },
  {
    title: 'Heineken',
    price: 'R$ 18',
    tags: '600ml',
  },
  {
    title: 'Amstel',
    price: 'R$ 12',
    tags: '600ml',
  },
  {
    title: 'Heineken',
    price: 'R$ 12',
    tags: 'Longneck',
  },
];

const cocktails = [
  {
    title: 'Aperol Sprtiz',
    price: '$20',
    tags: 'Aperol | Villa Marchesi prosecco | soda | 30 ml',
  },
  {
    title: "Dark 'N' Stormy",
    price: '$16',
    tags: 'Dark rum | Ginger beer | Slice of lime',
  },
  {
    title: 'Daiquiri',
    price: '$10',
    tags: 'Rum | Citrus juice | Sugar',
  },
  {
    title: 'Old Fashioned',
    price: '$31',
    tags: 'Bourbon | Brown sugar | Angostura Bitters',
  },
  {
    title: 'Negroni',
    price: '$26',
    tags: 'Gin | Sweet Vermouth | Campari | Orange garnish',
  },
];

const awards = [
  {
    imgUrl: images.award01,
    title: 'Projeto de Pesquisa da UEFS',
    subtitle: 'Sugerido por Natan Ourives.'
  },
  {
    imgUrl: images.award01,
    title: 'Automatizar o processo de consulta dos artigos.',
    subtitle: 'Sugerido por Arthur Teles',
  },
  {
    imgUrl: images.award01,
    title: 'Automatizar o processo de consulta das leis.',
    subtitle: 'Sugerido por Arthur Teles',
  },

];
const eventos = [
  {
      "Ano de Publicação": "1997",
      "Autores": "Ulhôa, M.",
      "Título da Produção": "Dissertações de Mestrado defendidas nos cursos de Pós-graduação Stricto Sensu em Música e Artes/Música até dezembro de 1996.",
      "Local da Publicação": "Revista Opus",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Música",
      "Tipos de Documentos Revisados": "Dissertações",
      "Local de Levantamento": "PPG´s Brasileiros",
      "Início do Recorte Cronológico": "01/01/1983",
      "Fim do Recorte Cronológico": "31/12/1996",
      "Total de Textos Levantados": 262,
      "Total de Textos Levantados em Música (M)": 262,
      "Total de Textos Levantados em Educação Musical (EM)": 50,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 3,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "1997",
      "Autores": "Oliveira, A. e Souza, J",
      "Título da Produção": "Pós-graduação em Educação Musical (resultados preliminares).",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical",
      "Tipos de Documentos Revisados": "Dissertações",
      "Local de Levantamento": "PPG´s Brasileiros",
      "Início do Recorte Cronológico": "01/01/1984",
      "Fim do Recorte Cronológico": "31/12/1997",
      "Total de Textos Levantados": 46,
      "Total de Textos Levantados em Música (M)": 46,
      "Total de Textos Levantados em Educação Musical (EM)": 46,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2000",
      "Autores": "Fernandes, J. N.",
      "Título da Produção": "Pesquisa em Educação Musical: situação do campo nas dissertações e teses dos cursos de pós-graduação stricto sensu em Educação.",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical",
      "Tipos de Documentos Revisados": "Dissertações e Teses",
      "Local de Levantamento": "PPG´s Brasileiros",
      "Início do Recorte Cronológico": "01/01/1981",
      "Fim do Recorte Cronológico": "31/12/1997",
      "Total de Textos Levantados": 106,
      "Total de Textos Levantados em Música (M)": 50,
      "Total de Textos Levantados em Educação Musical (EM)": 50,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 3,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2006",
      "Autores": "Fernandes, J. N.",
      "Título da Produção": "Pesquisa em Educação Musical: situação do campo nas dissertações e teses dos Cursos de Pós-Graduação Stricto Sensu Brasileiros.",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical",
      "Tipos de Documentos Revisados": "Dissertações e Teses",
      "Local de Levantamento": "PPG´s Brasileiros",
      "Início do Recorte Cronológico": "01/01/1998",
      "Fim do Recorte Cronológico": "31/12/2001",
      "Total de Textos Levantados": 125,
      "Total de Textos Levantados em Música (M)": 125,
      "Total de Textos Levantados em Educação Musical (EM)": 125,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 2,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2007",
      "Autores": "Fernandes, J. N.",
      "Título da Produção": "Pesquisa em educação musical: situação do campo nas dissertações e teses dos cursos de pós-graduação stricto sensu brasileiros (II).",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical",
      "Tipos de Documentos Revisados": "Dissertações e Teses",
      "Local de Levantamento": "PPG´s Brasileiros",
      "Início do Recorte Cronológico": "01/01/2002",
      "Fim do Recorte Cronológico": "31/12/2005",
      "Total de Textos Levantados": 142,
      "Total de Textos Levantados em Música (M)": 142,
      "Total de Textos Levantados em Educação Musical (EM)": 142,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 2,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 2,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2008",
      "Autores": "Santos, C. E.",
      "Título da Produção": "A Educação Musical Especial: aspectos históricos, legais e metodológicos (Capítulo 3, item 3.2 As concepções e abordagens da educação musical especial segundo a literatura).",
      "Local da Publicação": "Repositório Institucional da UNIRIO",
      "Tipo de Publicação": "Capítulo de Dissertação em Música",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas",
      "Local de Levantamento": "ABEM",
      "Início do Recorte Cronológico": "01/01/1993",
      "Fim do Recorte Cronológico": "31/12/2007",
      "Total de Textos Levantados": 10,
      "Total de Textos Levantados em Música (M)": 10,
      "Total de Textos Levantados em Educação Musical (EM)": 10,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 10,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 8,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 8
  },
  {
      "Ano de Publicação": "2009",
      "Autores": "Morales, D., Bellochio, C.",
      "Título da Produção": "A Educação Musical Especial em Produções dos Encontros Nacionais da ABEM.",
      "Local da Publicação": "Anais da ABEM Nacional",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos",
      "Local de Levantamento": "ABEM",
      "Início do Recorte Cronológico": "01/01/2002",
      "Fim do Recorte Cronológico": "31/12/2008",
      "Total de Textos Levantados": 40,
      "Total de Textos Levantados em Música (M)": 40,
      "Total de Textos Levantados em Educação Musical (EM)": 40,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 40,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 9,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 4
  },
  {
      "Ano de Publicação": "2014",
      "Autores": "Gums, L. M, Schambeck, R. F.",
      "Título da Produção": "Música e Educação Especial: produções online nas revistas e anais de encontros/congressos da Abem (1992 – 2012),",
      "Local da Publicação": "Anais da ABEM (Regional Sul)",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas",
      "Local de Levantamento": "ABEM",
      "Início do Recorte Cronológico": "01/01/1992",
      "Fim do Recorte Cronológico": "31/12/2012",
      "Total de Textos Levantados": 2258,
      "Total de Textos Levantados em Música (M)": 2258,
      "Total de Textos Levantados em Educação Musical (EM)": 2258,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 75,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 10,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 7
  },
  {
      "Ano de Publicação": "2016",
      "Autores": "Fantini, R. F. S.; Joly, I. Z., L. e Rose, T. M. S.",
      "Título da Produção": "Educação Musical Especial: produção brasileira nos últimos 30 anos.",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas, Dissertações e Teses.",
      "Local de Levantamento": "ABEM, SINCAM, ANPPOM, REE, RBEE, BTDC, BDTD e PPGEE´s",
      "Início do Recorte Cronológico": "01/01/1981",
      "Fim do Recorte Cronológico": "31/12/2015",
      "Total de Textos Levantados": 126,
      "Total de Textos Levantados em Música (M)": 126,
      "Total de Textos Levantados em Educação Musical (EM)": 126,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 126,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 5,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 3
  },
  {
      "Ano de Publicação": "2015",
      "Autores": "Tomás, L.",
      "Título da Produção": "A Pesquisa Acadêmica na Área da Música: um Estado da Arte (1988 -2013).",
      "Local da Publicação": "Livro da ANPPOM (Pesquisa em Música no Brasil)",
      "Tipo de Publicação": "Livro",
      "Campos de Revisão": "Música",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos",
      "Local de Levantamento": "ANPPOM",
      "Início do Recorte Cronológico": "01/01/1988",
      "Fim do Recorte Cronológico": "01/01/2013",
      "Total de Textos Levantados": 2650,
      "Total de Textos Levantados em Música (M)": 2650,
      "Total de Textos Levantados em Educação Musical (EM)": 546,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 30,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 5,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 4
  },
  {
      "Ano de Publicação": "2016",
      "Autores": "Pendeza, D. e Dallabrida, I. C.",
      "Título da Produção": "Educação Musical e Tea: um panorama das publicações nacionais.",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "EMPDIC - Transtorno do Espectro Autista",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos, Teses e Dissertações",
      "Local de Levantamento": "ABEM, ANNPOM, Portal de Periódicos Capes, Scielo, SINCAM e SIMPOM",
      "Início do Recorte Cronológico": "01/01/2005",
      "Fim do Recorte Cronológico": "01/01/2015",
      "Total de Textos Levantados": 19,
      "Total de Textos Levantados em Música (M)": 19,
      "Total de Textos Levantados em Educação Musical (EM)": 19,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 19,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 19,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 1
  },
  {
      "Ano de Publicação": "2018",
      "Autores": "Cil, L. R. e Gonçalves, T. G. G. L.",
      "Título da Produção": "Educação Musical e Educação Especial na Produção Científica de Dissertações e Teses",
      "Local da Publicação": "Revista Música Hodie",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Dissertações e Teses",
      "Local de Levantamento": "BTDC e BDTD",
      "Início do Recorte Cronológico": "01/01/1987",
      "Fim do Recorte Cronológico": "01/01/2016",
      "Total de Textos Levantados": 17,
      "Total de Textos Levantados em Música (M)": 17,
      "Total de Textos Levantados em Educação Musical (EM)": 17,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 17,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 1,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 1
  },
  {
      "Ano de Publicação": "2018",
      "Autores": "Zimmer, P. N.; Rodrigues, J. C. e DeFreitas, A. D.",
      "Título da Produção": "Educação Musical e Transtorno do Espectro Autista: análise da produção em revistas brasileiras de artes/música qualis A1 e seus anais de eventos regionais e nacionais.",
      "Local da Publicação": "Revista da ABEM",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "EMPDIC - Transtorno do Espectro Autista",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas",
      "Local de Levantamento": "Plataforma Sucupira: Música Hodie, Per Musi, Revista da ABEM, Revista OPUS, Anais Regionais e Nacionais da ABEM e da ANPPOM",
      "Início do Recorte Cronológico": "01/01/2006",
      "Fim do Recorte Cronológico": "01/01/2016",
      "Total de Textos Levantados": 3844,
      "Total de Textos Levantados em Música (M)": 3844,
      "Total de Textos Levantados em Educação Musical (EM)": "",
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 16,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 1,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": null
  },
  {
      "Ano de Publicação": "2019",
      "Autores": "Pereira, E. P. R",
      "Título da Produção": "A Educação Musical no Brasil: temáticas, concepções e linhas investigativas.",
      "Local da Publicação": "Repositório Institucional da Universidade de Santiago de Compostela (Espanha)",
      "Tipo de Publicação": "Tese de Estado da Arte em Educação Musical",
      "Campos de Revisão": "Educação Musical",
      "Tipos de Documentos Revisados": "Teses",
      "Local de Levantamento": "Plataforma Sucupira e Currículo Lattes",
      "Início do Recorte Cronológico": "01/01/1990",
      "Fim do Recorte Cronológico": "01/01/2017",
      "Total de Textos Levantados": 300,
      "Total de Textos Levantados em Música (M)": 300,
      "Total de Textos Levantados em Educação Musical (EM)": 300,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 7,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 0,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2019",
      "Autores": "Coutinho, G. A. D; Farias, M. S. N. C. e Damasceno, V. T. S.",
      "Título da Produção": "Música e Síndrome de Down: análise das publicações dos congressos da Associação Brasileira de Educação Musical (ABEM) de 2008-2018.",
      "Local da Publicação": "Anais da ABEM Nacional",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "EMPDIC - Síndrome de Down",
      "Tipos de Documentos Revisados": "Artigos de Anais em Eventos",
      "Local de Levantamento": "ABEM",
      "Início do Recorte Cronológico": "01/01/2008",
      "Fim do Recorte Cronológico": "01/01/2018",
      "Total de Textos Levantados": 13,
      "Total de Textos Levantados em Música (M)": 13,
      "Total de Textos Levantados em Educação Musical (EM)": 13,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 13,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 13,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 13
  },
  {
      "Ano de Publicação": "2019",
      "Autores": "Souza, C. L. e Sampaio, R. T.",
      "Título da Produção": "A Educação Musical Inclusiva no Brasil: uma revisão de literatura",
      "Local da Publicação": "Revista Olhares - Revista do Departamento de Educação da UNIFESP",
      "Tipo de Publicação": "Artigo",
      "Campos de Revisão": "Educação Musical Inclusiva",
      "Tipos de Documentos Revisados": "Artigos, TCCs, Dissertações e Teses",
      "Local de Levantamento": "Portal Capes, Cochrane, Pubmed e Google Acadêmico",
      "Início do Recorte Cronológico": "01/01/2014",
      "Fim do Recorte Cronológico": "01/01/2018",
      "Total de Textos Levantados": 3867,
      "Total de Textos Levantados em Música (M)": 3867,
      "Total de Textos Levantados em Educação Musical (EM)": 3867,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 16,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 10,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 3
  },
  {
      "Ano de Publicação": "2019",
      "Autores": "Paulino, D. F.",
      "Título da Produção": "Educação Musical Especial: uma revisão de literatura em publicações da ABEM (2014-2018)",
      "Local da Publicação": "Repositório Institucional da UNB",
      "Tipo de Publicação": "TCC de Licenciatura em Música",
      "Campos de Revisão": "Educação Musical Especial",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas",
      "Local de Levantamento": "ABEM",
      "Início do Recorte Cronológico": "01/01/2014",
      "Fim do Recorte Cronológico": "01/01/2018",
      "Total de Textos Levantados": 33,
      "Total de Textos Levantados em Música (M)": 33,
      "Total de Textos Levantados em Educação Musical (EM)": 33,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 5,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 3,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2020",
      "Autores": "Tomás, L.",
      "Título da Produção": "\"Leituras de Brasil\" nas pesquisas acadêmicas da área da música",
      "Local da Publicação": "Livro da ANPPOM (Pesquisa em Música no Brasil)",
      "Tipo de Publicação": "Livro",
      "Campos de Revisão": "Música",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos",
      "Local de Levantamento": "ANPPOM",
      "Início do Recorte Cronológico": "01/01/2014",
      "Fim do Recorte Cronológico": "01/01/2018",
      "Total de Textos Levantados": 1360,
      "Total de Textos Levantados em Música (M)": 1360,
      "Total de Textos Levantados em Educação Musical (EM)": 264,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 21,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 3,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  },
  {
      "Ano de Publicação": "2024",
      "Autores": "Pereira, G. de L.",
      "Título da Produção": "Desenvolvimento Musical de Estudantes com Transtorno do Espectro Autista (TEA) (Capítulo 3 - Música e Autismo: uma revisão integrativa da literatura)",
      "Local da Publicação": "Repositório Institucional da UEFS",
      "Tipo de Publicação": "TCC de Licenciatura em Música",
      "Campos de Revisão": "EMPDIC - Transtorno do Espectro Autista",
      "Tipos de Documentos Revisados": "Artigos em Anais de Eventos e Revistas",
      "Local de Levantamento": "Revista Orfeu, da ABEM, Per Musi, Musica Hodie, Vórtex, Opus e Anais da ABEM e ISME",
      "Início do Recorte Cronológico": "01/01/2014",
      "Fim do Recorte Cronológico": "01/01/2023",
      "Total de Textos Levantados": 24,
      "Total de Textos Levantados em Música (M)": 24,
      "Total de Textos Levantados em Educação Musical (EM)": 24,
      "Total de Textos Levantados em Educação Musica Especial e Inclusiva (EMEI)": 24,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual e Comorbidades (EMPDIC)": 24,
      "Total de Textos Levantados em Educação Musical de Pessoas com Deficiência Intelectual (EMPDI)": 0
  }
]



export default { wines, cocktails, awards, eventos };
